version: '3.2'

services:
  db:
    image: postgres:10
    restart: unless-stopped
    volumes:
      - db_short_links:/var/lib/postgresql/data
    networks:
      - webnet
    ports:
      - "5432:5432"
    env_file: ./config/.env

  web:
    <<: &web
      build:
        context: .
        dockerfile: ./docker/django/Dockerfile
        args:
          DJANGO_ENV: development
      restart: unless-stopped
      volumes:
        - .:/code
        - django-static:/var/www/django/static
      ports:
        - "8000:8000"
      depends_on:
        - db
      networks:
        - webnet
      env_file: ./config/.env
      environment:
        DJANGO_DATABASE_HOST: db
    command: python3 -Wd manage.py runserver 0.0.0.0:8000


networks:
  webnet:

volumes:
  db_short_links:
  django-static:
  django-media:
